### ISSUE TITLE
The Menu Bold Style Makes "The Width Inconsitent"

### ISSUE THREAD

**Issue by mufid** [Code4Nation/hackathon#39]
Example:

![2015-09-16_04-46-51](https://cloud.githubusercontent.com/assets/430505/9891073/fb537b60-5c2d-11e5-8a38-ba83d2071e80.gif)

If you hover a menu text over that, the other text on that header is moving too (which is annoying).

I think each menu element must we wrapped in a fixed-width element.

**Comment by irvan-putra** [comment]
Wow, nice catch!

@khairulanshar might be interested.

Anyone has suggestion?

**Comment by irvan-putra** [comment]
Fixed by @khairulanshar ...by not using bold style.
