### ISSUE TITLE
Perlu dibuatkan FAQ

### ISSUE THREAD

**Issue by santosoide** [Code4Nation/hackathon#72]
Mungkin perlu dibuatkan FAQ, bisa jadi karena ini diadakan disetiap kota yang terdekat nama - nama baru akan muncul, yang mana mereka sangat asing dengan istilah atau peraturan technical dalam event hackathon.

beberapa poin yang saya ajukan:
- Apa itu Hackathon?
- Siapa saja yang boleh mengikuti?
- Apa yang harus saya bawa?
- Bagaimana membentuk atau bergabung dengan tim dan mengapa?
- Jika sudah ikut dan membuat aplikasi, siapa nanti yang akan memiliki hak lisensi dari aplikasi?
- Bahasa pemrograman atau perangkat keras apa saja yang diperbolehkan?
- Apakah ada hadiah untuk kategori hackathon kali ini?
- Setelah mengikuti acara ini apa yang saya dapatkan?

**Comment by irvan-putra** [comment]
Iya, ini kelupaan. Saya jawab dulu, nanti belakangan bikin commitnya... atau @cyberid41 mau bikinin?
- Apa itu Hackathon?

Hacker biasanya selalu dikonotasikan negatif dan berkaitan dengan pembobolan komputer. Sebenarnya pengertian hacker adalah seseorang yg ahli di bidang teknologi, memiliki kemampuan membangun, menganalisa kelemahan ataupun kelebihan, dan memperbaiki serta membuat terobosan atas software maupun hardware. „Hackathon“ adalah penggabungan kata hacker dan marathon, artinya aktivitas analisa, membangun, menerobos sesuatu dengan konsisten dalam kurun waktu tertentu (seperti lari marathon). Hackaton Merdeka merupakan aktivitas hackathon yang dilakukan untuk bersama me"merdeka"kan Indonesia.

Gerakan ini berpotensi untuk memulai sejarah kerjasama pemerintah dan masyarakat.
- Apa ini hanya untuk developer berpengalaman?

Tidak. Semua warga negara Indonesia bisa berpartisipasi.
- Apa yang harus saya bawa?

Apa saja yang membantu Anda menyelesaikan aplikasi dan presentasi. Silahkan membawa peralatan selama itu tidak menyulitkan Anda.
- Bagaimana membentuk atau bergabung dengan tim dan mengapa?

Diwajibkan kamu sudah memperkenalkan diri di forum code4nation.id, untuk memudahkan komunikasi sesudah acara. Kalau bisa, bentuk tim jauh-jauh hari sebelum acara.
- Jika sudah ikut dan membuat aplikasi, siapa nanti yang akan memiliki hak lisensi dari aplikasi?

Publik, supaya bisa dikembangkan bersama-sama.
- Bahasa pemrograman atau perangkat keras apa saja yang diperbolehkan?

Apa saja asal boleh digunakan oleh publik dan mempertimbangkan kegunaannya.
- Apakah ada hadiah untuk kategori hackathon kali ini?

Belum ada.
- Setelah mengikuti acara ini apa yang saya dapatkan?

Hackathon ini memberikan permasalahan nyata, yang menyangkut hajat hidup orang banyak, serta membangun negeri. Tantangannya pun didesain untuk tidak hanya memanfaatkan teknologi dan informasi yang sudah ada, tapi juga mendorong pembuatan sistem teknologi informasi baru.

Kami tahu kamu ingin berkontribusi untuk membantu hajat hidup orang banyak di negeri tercinta.

**Comment by santosoide** [comment]
sip :+1:  sudah saya siapkan sebenarnya cuman saya gag ahli dalam olah kata

**Comment by irvan-putra** [comment]
@cyberid41 ditunggu PR-nya :D

**Comment by santosoide** [comment]
sudah bang @vandeput #73
